config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root 'welcome#index' 
  get '/about', to: 'pages#about', as: 'about'
  get '/index', to: 'pages#index', as: 'Home'
  get '/content', to: 'pages#content', as: 'Content'

resources :parks, only: [:index]
resources :wildlife, only: [:index]
resources :visitors, only: [:index]
resources :facilities, only: [:index]

resources :parks, only: [:show]
resources :wildlife, only: [:show]
resources :visitors, only: [:show]
resources :facilities, only: [:show]


resources :parks do
  resources :wildlife, only: [:show]
  resources :visitors, only: [:show]
  resources :facilities, only: [:show]
end

resources :wildlife, only: [:show]
resources :visitors, only: [:show]
resources :facilities, only: [:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/facility.rb
class Facility < ApplicationRecord
    has_many :park_facilities
    
  has_many :parks, through: :park_facilities
  validates_presence_of :name, :description
end

app/models/park.rb
class Park < ApplicationRecord
  
  has_many :park_facilities
  has_many :facilities, through: :park_facilities
  
    has_many :visitors
  has_many :wildlife
  validates_presence_of :name, :location, :established_date, :size

  include PgSearch::Model
  pg_search_scope :search_by_name_and_location, against: [:name, :location]

end

app/models/park_facility.rb
class ParkFacility < ApplicationRecord

    belongs_to :park
    belongs_to :facility
    
  end
  

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :park
  validates_presence_of :year, :total_visitors, :camping_visitors
end

app/models/wildlife.rb
class Wildlife < ApplicationRecord
  belongs_to :park
  validates_presence_of :species_name, :habitat, :population_status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
    def index
        @facilities = Facility.all
      end
      def show
        @facility = Facility.find(params[:id])
        @parks = @facility.parks.first
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def home
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    def index
      if params[:query].present?
        @parks = Park.search_by_name_and_location(params[:query]).paginate(page: params[:page], per_page: 10)
      else
        @parks = Park.paginate(page: params[:page], per_page: 10)
      end
      @parks = @parks.where(category: params[:category]) if params[:category].present?
    end
      
      def show
        @park = Park.find(params[:id])
        @parks = [@park] 
        @visitors = @park.visitors
        @facilities = @park.facilities
        @wildlife = @park.wildlife
      end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    def index
      @visitors = Visitor.paginate(page: params[:page], per_page: 10)
      end
      def show
        @visitor = Visitor.find(params[:id])
        @park = @visitor.park
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wildlife_controller.rb
class WildlifeController < ApplicationController
    def index
      @wildlife = Wildlife.paginate(page: params[:page], per_page: 10)
      end
      def show
        @wildlife = Wildlife.find(params[:id])
        @park = @wildlife.park
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wildlife_helper.rb
module WildlifeHelper
end

app/views/facilities/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>List of Facilities</title>
  <%= stylesheet_link_tag 'facilities' %>
</head>
<body>
  <h1>List of Facilities</h1>
  <ul>
    <% @facilities.each do |facility| %>
      <li><%= facility.name %></li>
    <% end %>
  </ul>
</body>
</html>

app/views/facilities/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Facility Details</title>
</head>
<body>
  <h1>Facility Name: <%= @facility.name %></h1>
  <h2>Park:</h2>
  <p><%= link_to @parks.name, park_path(@parks) %></p>
</body>
</html>

app/views/parks/index.html.erb
<head>
<%= stylesheet_link_tag 'parks' %>
<%= paginate @parks %>
</head>

<body>
<h1>List of National Wildlife Parks</h1>

<%= form_tag(parks_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search parks..." %>
  <%= select_tag :category, options_for_select(["Location", "established_on", "size"], params[:category]), include_blank: "All Categories" %>
  <%= submit_tag "Search" %>
<% end %>

<ul class="pagination">
  <% @parks.each do |park| %>
    <li><%= link_to park.name, park_path(park) %></li>
  <% end %>
</ul>

<% if @parks.empty? %>
  <p>No parks found.</p>
<% else %>
  <ul>
    <% @parks.each do |park| %>
      <li><%= park.name %></li>
    <% end %>
  </ul>
<% end %>

</body>

app/views/parks/show.html.erb
<h1>Park: <%= @park.name %></h1>
<p>Park Location: <%= @park.location %></p>
<p>Park Established On : <%= @park.established_date %></p>
<p>Park Size: <%= @park.size %></p>
<p>Park Description: <%= @park.description %></p>

<h2>Wildlife:</h2>
<ul>
  <% @wildlife.each do |wildlife| %>
    <li><%= link_to wildlife.species_name, wildlife_path(wildlife)%></li>
  <% end %>
</ul>

<h2>Visitors:</h2>
<ul>
  <% @visitors.each do |visitor| %>
    <li><%= link_to visitor.total_visitors, visitor_path(visitor) %></li>
  <% end %>
</ul>

<h2>Facilities:</h2>
<ul>
  <% @facilities.each do |facility| %>
    <li><%= link_to facility.name, facility_path(facility) %></li>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <% if @parks.empty? %>
        <p>No parks found.</p>
      <% else %>
        <ul>
          <% @parks.each do |park| %>
            <li><%= park.name %></li>
          <% end %>
        </ul>
      <% end %>
      
    </div>
  </div>
</div>

</ul>

app/views/visitors/index.html.erb
<head>
<%= stylesheet_link_tag 'visitors' %>
</head>
<body>

<h1>List of Total Number Of Visitors</h1>

<ul class="pagination">
<%= paginate @visitors %>
     <% @visitors.each do |visitor| %>
    <li><%= link_to visitor.total_visitors, visitors_path(visitor) %></li>
  <% end %>
</ul>

</body>

app/views/visitors/show.html.erb
<h1>Visitor Year: <%= @visitor.year %></h1>
<p>Total Visitors in the Year: <%= @visitor.total_visitors %></p>
<p>Total Camping Visitors in the Year: <%= @visitor.camping_visitors %></p>

<h2>Park:</h2>

<p><%= link_to @park.name, park_path(@park) %></p>

app/views/wildlife/index.html.erb
<head>
<%= stylesheet_link_tag 'wildlife' %>
</head>

<body>
<h1>List of Wildlife</h1>
<%= paginate @wildlife %>
<ul>
  <% @wildlife.each do |wildlife| %>
    <li><%= link_to wildlife.species_name, wildlife_path(wildlife) %></li>
  <% end %>
</ul>

</body>

app/views/wildlife/show.html.erb
<h1>Species Name: <%= @wildlife.species_name %></h1>
<p>Population: <%= @wildlife.population_status %></p>
<p>Habitat of the Species: <%= @wildlife.habitat %></p>

<h2>Park:</h2>
<p><%= link_to @park.name, park_path(@park)  %></p>