config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root 'welcome#index' 
  get '/about', to: 'pages#about', as: 'about'
  get '/index', to: 'pages#index', as: 'Home'
  get '/content', to: 'pages#content', as: 'Content'

resources :parks, only: [:index]
resources :wildlife, only: [:index]
resources :visitors, only: [:index]
resources :facilities, only: [:index]

resources :parks, only: [:show]
resources :wildlife, only: [:show]
resources :visitors, only: [:show]
resources :facilities, only: [:show]


resources :parks do
  resources :wildlife, only: [:show]
  resources :visitors, only: [:show]
  resources :facilities, only: [:show]
end

resources :wildlife, only: [:show]
resources :visitors, only: [:show]
resources :facilities, only: [:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/facility.rb
class Facility < ApplicationRecord
    has_many :park_facilities
    
  has_many :parks, through: :park_facilities
  validates_presence_of :name, :description
end

app/models/park.rb
class Park < ApplicationRecord
  
  has_many :park_facilities
  has_many :facilities, through: :park_facilities
  
    has_many :visitors
  has_many :wildlife
  validates_presence_of :name, :location, :established_date, :size

  include PgSearch::Model
  pg_search_scope :search_by_name_and_location, against: [:name, :location]

end

app/models/park_facility.rb
class ParkFacility < ApplicationRecord

    belongs_to :park
    belongs_to :facility
    
  end
  

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :park
  validates_presence_of :year, :total_visitors, :camping_visitors
end

app/models/wildlife.rb
class Wildlife < ApplicationRecord
  belongs_to :park
  validates_presence_of :species_name, :habitat, :population_status
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
    def index
        @facilities = Facility.all
      end
      def show
        @facility = Facility.find(params[:id])
        @parks = @facility.parks.first
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def home
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    def index
      if params[:query].present?
        @parks = Park.search_by_name_and_location(params[:query]).paginate(page: params[:page], per_page: 10)
      else
        @parks = Park.paginate(page: params[:page], per_page: 10)
      end
      @parks = @parks.where(category: params[:category]) if params[:category].present?
    end
      
      def show
        @park = Park.find(params[:id])
        @parks = [@park] 
        @visitors = @park.visitors
        @facilities = @park.facilities
        @wildlife = @park.wildlife
      end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    def index
      @visitors = Visitor.paginate(page: params[:page], per_page: 10)
      end
      def show
        @visitor = Visitor.find(params[:id])
        @park = @visitor.park
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wildlife_controller.rb
class WildlifeController < ApplicationController
    def index
      @wildlife = Wildlife.paginate(page: params[:page], per_page: 10)
      end
      def show
        @wildlife = Wildlife.find(params[:id])
        @park = @wildlife.park
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wildlife_helper.rb
module WildlifeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NationalWildlifeParks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>

     <%= javascript_importmap_tags %>

    <style>
        .menu {
            display: flex;
            justify-content: space-around;
            background-color: #336;
            padding: 10px;
        }
        .menu a {
            color: white;
            text-decoration: none;
        }

        .menu a:hover {
            color: #ddd;
        }
    </style>
 </head>
 <body>
   <div class="menu">
     <a href="index.html">Home</a>
     <a href="about.html">About</a>
    <a href="content.html">Content</a>
   </div>
   
    <%= yield %>
    
</body
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Page</title>
    <%= stylesheet_link_tag 'about' %>
</head>

<body>
    <header>
        <h1>National Wildlife Parks</h1>
        <h2>My rails Application</h2>
    </header>

    <main>
    
        <section>
            <h2>Data Sources</h2>
            <p>My rails application uses the following data sources:</p>
            <ol>
                <li>Parks: 100 randomly generated parks with details such as name, location, established date, size, and description.</li>
                <li>Visitors: 200 randomly generated visitors with details such as park ID, year, total visitors, and camping visitors.</li>
                <li>Wildlife: 200 randomly generated wildlife records with details such as park ID, species name, habitat, and population status.</li>
                <li>Facilities: Randomly generated facilities such as visitor centers, picnic areas, playgrounds, and trails.</li>
            </ol>
        </section>
        <section>
            <h2>Entity Relationship Diagram (ERD)</h2>
            <p>My Rails application ERD represents the relationships between the Park, Visitor, Wildlife, and Facility entities.</p>
            <img src="<%= image_path('erd.jpg') %>" alt="ERD">


        </section>
    </main>
    <footer>
        <p>&copy; 2024 My Rails Application. All rights reserved.</p>
    </footer>
</body>
</html>

app/views/pages/content.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Application</title>
  <%= stylesheet_link_tag 'content' %>
  </head>
<body>

  <ul>
    <li><%= link_to "Parks", parks_path %></li>
    <li><%= link_to "Wildlife", wildlife_index_path %></li>
    <li><%= link_to "Visitors", visitors_path %></li>
    <li><%= link_to "Facilities", facilities_path %></li>
  </ul>
  

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>National Wildlife Parks</title>
    <%= stylesheet_link_tag 'index' %>
</head>
<body>
    <header>
        <h1>Welcome to National Wildlife Parks</h1>
    </header>
    <main>
        <h2>Explore the Beauty of Nature</h2>
        <p>Discover our national parks unique animals and stunning scenery. From the lush wetlands of the Everglades to the breathtaking mountains of Yosemite, there is something to enjoy for everyone. Numerous activities, such as hiking, camping, seeing wildlife, and more, are available in our parks. Begin organizing your journey now!</p>

    <footer>
        <p>&copy; 2023 National Wildlife Parks. All rights reserved.</p>
    </footer>
</body>
</html>